version: '3.8'

services:
  elasticsearch:
    image: elasticsearch:8.1.3
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false # elasticsearch 8.x版本後會自動開啟SSL
    networks:
      efk_network:
        ipv4_address: 172.20.0.3
    ports:
      - 9200:9200

  kibana:
    image: kibana:8.1.3
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    # - I18N_LOCALE=zh-CN
    networks:
      efk_network:
        ipv4_address: 172.20.0.4
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch

  fluentd:
    build: ../fluentd
    container_name: fluentd
    volumes:
      - ../docker-volume/fluentd:/fluentd/etc
    depends_on:
      - elasticsearch
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    networks:
      efk_network:
        ipv4_address: 172.20.0.5

networks:
  efk_network:
    driver: bridge
    name: efk_network
    ipam:
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.1
